In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [5]:
df = pd.read_csv("../data/raw/po_late_delivery_dataset.csv")

df.head()

,po_id,supplier_id,supplier_name,supplier_country,material_category,material_criticality,order_date,promised_delivery_date,quantity_ordered,unit_price_usd,...,shipping_method,distance_km,supplier_lead_time_avg_days,supplier_otd_rate_historical_pct,supplier_active_pos_count,is_peak_season,actual_delivery_date,delay_days,goods_receipt_status,is_late
0,PO-2025-002296,SUP-026,Supplier Generic 26,Indonesia,Packaging,Medium,2025-02-10,2025-02-15,663,NaN,...,Courier,317.0,2.0,83.4,9,0,2025-02-13,-2,Complete,0
1,PO-2024-001711,SUP-008,Shenzhen Precision Metals,South Korea,Component,Low,2024-12-22,2025-01-13,336,4.11,...,Sea,4218.2,14.4,61.0,7,1,2025-01-12,-1,Complete,0
2,PO-2024-002451,SUP-038,Supplier Generic 38,China,Raw Material,Low,2024-03-04,2024-03-19,805,10.37,...,air,3712.0,19.9,70.2,3,1,2024-03-17,-2,Complete,0
3,PO-2025-002269,SUP-036,Supplier Generic 36,Indonesia,Raw Material,High,2025-03-21,2025-03-26,1082,17.64,...,Land,339.5,3.4,40.0,8,1,2025-03-24,-2,Complete,0
4,PO-2024-001219,SUP-008,Shenzhen Precision Metals,South Korea,MRO,Low,2024-10-09,2024-10-23,454,6.69,...,Air,4691.6,14.4,61.0,12,0,2024-10-21,-2,Complete,0

In [12]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 2506 entries, 0 to 2505
Data columns (total 22 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   po_id                             2506 non-null   str
 1   supplier_id                       2506 non-null   str
 2   supplier_name                     2506 non-null   str
 3   supplier_country                  2506 non-null   str
 4   material_category                 2506 non-null   str
 5   material_criticality              2506 non-null   str
 6   order_date                        2506 non-null   str
 7   promised_delivery_date            2506 non-null   str
 8   quantity_ordered                  2506 non-null   int64
 9   unit_price_usd                    2431 non-null   float64
 10  order_value_usd                   2431 non-null   float64
 11  payment_terms                     2469 non-null   str
 12  shipping_method                   2506 non-null   str
 13  distance_km                       2506 non-null   float64
 14  supplier_lead_time_avg_days       2506 non-null   float64
 15  supplier_otd_rate_historical_pct  2456 non-null   float64
 16  supplier_active_pos_count         2506 non-null   int64
 17  is_peak_season                    2506 non-null   int64
 18  actual_delivery_date              2506 non-null   str
 19  delay_days                        2506 non-null   int64
 20  goods_receipt_status              2506 non-null   str
 21  is_late                           2506 non-null   int64
dtypes: float64(5), int64(5), str(12)
memory usage: 699.1 KB
None

In [13]:
df.describe()

,quantity_ordered,unit_price_usd,order_value_usd,distance_km,supplier_lead_time_avg_days,supplier_otd_rate_historical_pct,supplier_active_pos_count,is_peak_season,delay_days,is_late
count,2.506000e+03,2431.000000,2431.000000,2506.000000,2506.000000,2456.000000,2506.000000,2506.000000,2506.000000,2506.000000
mean,2.905577e+03,16.659338,18815.054636,4281.112490,15.821389,71.618526,5.718276,0.325619,0.580607,0.232642
std,3.600869e+04,16.820779,36028.579608,4025.598592,7.093030,16.685183,2.583002,0.468699,4.408313,0.422600
min,1.900000e+01,-34.590000,187.520000,236.100000,2.000000,40.000000,1.000000,0.000000,-3.000000,0.000000
25%,3.362500e+02,6.955000,3437.250000,1796.600000,10.200000,59.500000,4.000000,0.000000,-2.000000,0.000000
50%,6.890000e+02,11.810000,8068.590000,3349.750000,17.800000,73.900000,6.000000,0.000000,-1.000000,0.000000
75%,1.390000e+03,20.665000,19735.700000,5363.300000,20.200000,83.400000,7.000000,1.000000,0.000000,0.000000
max,1.107163e+06,320.000000,595952.550000,19467.000000,30.500000,99.000000,17.000000,1.000000,14.000000,1.000000

## Cek Missing Value

In [9]:
missing = df.isna().sum()
missing_0 = missing[missing > 0]
missing_pct = missing_0 / len(df) * 100
missing_df = pd.DataFrame({
    "Missing": missing_0,
    "missing %": missing_pct
})
print(missing_df)

                                  Missing  missing %
unit_price_usd                         75   2.992817
order_value_usd                        75   2.992817
payment_terms                          37   1.476457
supplier_otd_rate_historical_pct       50   1.995211

In [11]:
df.groupby(df['unit_price_usd'].isna())['material_category'].value_counts()

unit_price_usd  material_category
False           Raw Material         829
                Component            755
                Packaging            485
                MRO                  362
True            Raw Material          26
                Component             22
                Packaging             17
                MRO                   10
Name: count, dtype: int64

## Inkonsistensi Kategorikal

In [ ]:
for col in df.columns:
    if df[col].dtype == object: